### ISSUE TITLE
pipeline-ui loading failed over https

### ISSUE THREAD

**Issue by zedgu** [rancher/pipeline-ui#3]
## URL
> https://<domain>/r/projects/1a5/pipeline-ui/#/fail

## Console Error
> Mixed Content: The page at 'https://<domain>/r/projects/1a5/pipeline-ui/' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://<domain>/r/projects/1a5/pipeline-server:60080/v1/pipelines?limit=-1&sort=name'. This request has been blocked; the content must be served over HTTPS.

**Comment by aaronwng** [comment]
@zedgu Could you specify your Issues more?
Which version is your Pipeline and rancher/server?
And Please give more detailed reproduce steps.

**Comment by zedgu** [comment]
Hi @biblesyme ,
more infomation here:

rancher: v1.16.13
pipeline: v0.1.1 (from Rancher Community catalog)

It's using https via traefik on the rancher, and then just click the 'pipeline' on the top nav, you never can open the pipline-ui.( but it works fine when i was using internal ip via http request)

> public_ip:443 -> traefik -> lb service of rancher(8080) -> external service of rancher (pointed to rancher_host_ip)

**docker-compose.yml**
```yml
version: '2'
services:
  Internal-LB:
    image: rancher/lb-service-haproxy:v0.7.15
    expose:
    - 8080:8080/tcp
    labels:
      io.rancher.container.agent.role: environmentAdmin,agent
      traefik.enable: 'true'
      traefik.port: '8080'
      traefik.domain: mydomain
      io.rancher.container.create_agent: 'true'
      traefik.frontend.passHostHeader: 'true'
      traefik.frontend.entryPoints: http,https
      traefik.http.redirect: https
      traefik.frontend.rule: Host:mydomain
      io.rancher.container.agent_service.drain_provider: 'true'
      traefik.sticky: 'true'
      traefik.acme: 'true'
  rancher:
    image: rancher/external-service
```

**rancher-compose.yml**
```yml
version: '2'
services:
  Internal-LB:
    scale: 1
    start_on_create: true
    lb_config:
      certs: []
      port_rules:
      - priority: 4
        protocol: tcp
        service: rancher
        source_port: 8080
        target_port: 8080
        weight: 0
    health_check:
      healthy_threshold: 2
      response_timeout: 2000
      port: 42
      unhealthy_threshold: 3
      initializing_timeout: 60000
      interval: 2000
      reinitializing_timeout: 60000
  rancher:
    external_ips:
    - 172.18.1.4
    start_on_create: true
```
